### ISSUE TITLE
Path resolution wrong

### ISSUE THREAD

**Issue by Dabassman** [etas/SonarLink#31] opened 2020-10-24 11:50 UTC
In ErrorListProvider.cs, the reg ex to match the path in line 90:

var regexString = projectDirectoryName.Replace("\\", "\\\\");

is defined too wide. If you have paths that are substrings of others, path resolution is wrong. I don't know how to debug studio plugins, but I assume the problem is our project structure which is (simplified)

root
-- \Service\Implementation.cs
--\AService\Implemention.cs
--\BService\Implementation.cs

I am not a reg ex wizard, but I think the reg ex has to be changed to match the complete path, not only parts of it. Additionally, in this case the method returns the path without \, leading to resolved file paths like

d:\root\AImplementation.cs

(assuming the structure given above).

**Comment by Dabassman** [comment] 2020-10-24 17:11
By the way: why are you searching for the directory? If I set the solution base path, the file path returned by sonar can be directly appended.

**Comment by guwirth** [comment] 2020-10-25 09:26
Hi @Dabassman,

thanks for the feedback, we will have a look.

Regards

**Comment by netspiri** [comment] 2020-12-30 12:44
Mentioned issue reproduced with a unit test.

As correctly noted by @Dabassman, directory hierarchies similar to the ones below:
* ~/Service/Impl.cs
* ~/AService/Impl.cs
* ~/BService/Impl.cs
* ~/Service/Service/Impl.cs
cause the regular expression mechanism to trigger unexpected matches and thus generate file paths to unexpected locations.

As mentioned, this can be simply fixed by assuming that the user's 'Set Local Path' directory is the root of the SonarQube project at which point we can simply concatenate the root with the Sonar provided path.

In our original/current implementation we had opted to allow users to select root paths which may be approximate and the implementation would try to find the root location based on the approximate path e.g. user 'Set Local Path' to `C:\` and SonarLink tries to identify a suitable project root from the underlying hierarchy. This operation is inherently expensive but alleviates the user from knowing the exact sonar-scanner root folder used to scan the project.

We can opt to revise our original design decision to allow approximate paths when using 'Set Local Path' and expect users to point to the appropriate Sonar root folder. This simplifies the design and implementation considerably at the cost of having users knowing the exact root path (which can be easily identified by navigating to the 'Code' tab in the SonarQube WEB interface).

**Comment by guwirth** [comment] 2021-01-05 09:16
@netspiri thanks for your investigation.

Maybe a combination of both approaches is the best?
1. Allowing to add an approximate root path, e.g. user 'Set Local Path' to C:\. Find 'suitable' path.
2. Set and display the exact (suitable) path then. If this is not the right one user must edit it again.
3. Internally we are using only the exact path from 'Set Local Path'.

@netspiri what are you thinking?

**Comment by netspiri** [comment] 2021-01-06 07:50
At this point the issue boils down to a matter of user experience. Offering multiple options may clutter the UI and may confuse users.

@Dabassman assumed that 'Set Local Path' requires the directory to be equivalent to that of the scanning root. This is a reasonable assumption, especially given that we never documented nor hinted about 'approximate' paths. In addition, since each project requires its own path, having approximate paths specified for each and every project may not be good use.

@guwirth Our recommendation is to simplify the logic and remove 'approximate' paths as @Dabassman suggested

**Comment by guwirth** [comment] 2021-01-07 16:16
@netspiri think you are right, the KISS approach is the best one.

**Closed** 2021-02-01 22:09 UTC
Labels: enhancement
